# Relases a pacakge and publish to pypy and readthedocs

name: Publish package

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      my_version:
        description: 'My version'
        required: true
        default: 'v0.0.10'
      my_description:
        description: 'My description'
        required: true
        default: 'Some text'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Create Version
      run: |
        git tag
        git describe --tags --abbrev=0 
        echo "TAG_STRING=$(git describe --tags --abbrev=0 | sed -e s/v//g)" >> $GITHUB_ENV
    - name: Get version
      run: |
        echo "------------------------"
        echo "${{ env.TAG_STRING }}" 
        echo "------------------------"
    - name: Create changelog
      run: |
        chmod +x ./scripts/rz.py
        # ./scripts/rz.py create ${{ env.TAG_STRING }}
    - name: Commit and Push Changelog
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Update changelog for v${{ env.TAG_STRING }}'
        add: 'CHANGELOG.md'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create wheel and publish to pypi
      env:
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        git tag -d ${{ env.TAG_STRING }}
        git tag ${{ env.TAG_STRING }}
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools_scm twine
        python setup.py bdist_wheel        
        python -m twine check dist/*
        python -m twine upload dist/* -u${{ secrets.PYPI_USER }} -p"${{ secrets.PYPI_PASSWORD }}"
        mv dist/swiss*.whl dist/swissarmyknife-${{ env.TAG_STRING }}.whl





    - name: Release package
      uses: ncipollo/release-action@v1
      with:       
        tag: v${{ env.TAG_STRING }}
        name: Release v${{ env.TAG_STRING }}
        bodyFile: ./.tmprz/release_notes.md
        artifacts: dist/swissarmyknife-${{ env.TAG_STRING }}.whl
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
