# Relases a pacakge and publish to pypy and readthedocs

name: Publish package

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      my_version:
        description: 'My version'
        required: true
        default: 'v0.0.10'
      my_description:
        description: 'My description'
        required: true
        default: 'Some text'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Create Version
      run: |
        echo "TAG_STRING=$(git describe --tags --abbrev=0 | sed -e s/v//g)" >> $GITHUB_ENV
    - name: Create changelog
        chmod +x ./scripts/rz.py
        ./scripts/rz.py create ${{ env.TAG_STRING }}
    - name: Commit and Push Changelog
      uses: EndBug/add-and-commit@v7.4.0
      with:
        default_author: github_actions
        message: 'Update changelog for v${{ env.TAG_STRING }}'
        add: 'CHANGELOG.md'
        tag: v${{ env.TAG_STRING }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create wheel
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools_scm 
        python setup.py bdist_wheel
        ls dist
    - name: Get version
      run: |
        echo "------------------------"
        echo "${{ env.TAG_STRING }}"
        ls dist
        echo "------------------------"

    - name: Release package
      uses: ncipollo/release-action@v1
      with:       
        tag: v${{ env.TAG_STRING }}
        name: Release v${{ env.TAG_STRING }}
        bodyFile: ./.tmprz/release_notes.md
        artifacts: "./CHANGELOG.md"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
