# Relases a pacakge and publish to pypy and readthedocs

name: Publish package

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      my_version:
        description: 'My version'
        required: true
        default: 'v0.0.10'
      my_description:
        description: 'My description'
        required: true
        default: 'Some text'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Echo
      run: |
        echo "My description: ${{ github.event.inputs.my_description }}"
        echo "My Version: ${{ github.event.inputs.my_version }}"
        echo "Git Version: ${{ github.event.inputs.version }}"
               
    - id: get_version
      uses: battila7/get-version-action@v2
    - name: Get version
      run: |
        git tag
        ls 
        ls .git/refs/tags
        echo "------------------------"
        echo ${{ steps.get_version.outputs.version-without-v }}
        echo ${{ steps.get_version.outputs.version }}
        echo "------------------------"
