# Relases a pacakge and publish to pypy and readthedocs

name: Publish package

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      my_version:
        description: 'My version'
        required: true
        default: 'v0.0.10'
      my_description:
        description: 'My description'
        required: true
        default: 'Some text'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - id: get_version
      uses: battila7/get-version-action@v2

    - run: echo ${{ steps.get_version.outputs.version-without-v }}

    - uses: actions/checkout@v2
    - name: Echo
      run: |
        echo "My description: ${{ github.event.inputs.my_description }}"
        echo "My Version: ${{ github.event.inputs.my_version }}"
        echo "Git Version: ${{ github.event.inputs.version }}"
