# Relases a pacakge and publish to pypy and readthedocs

name: Publish package

on:
  push:
    branches: [ master ]

  workflow_dispatch:
    inputs:
      my_version:
        description: 'My version'
        required: true
        default: 'v0.0.10'
      my_description:
        description: 'My description'
        required: true
        default: 'Some text'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Echo
      run: |
        echo "TAG_STRING=$(git describe --tags --abbrev=0 | sed -e s/v//g)" >> $GITHUB_ENV
        echo "My description: ${{ github.event.inputs.my_description }}"
        echo "My Version: ${{ github.event.inputs.my_version }}"
        echo "Git Version: ${{ github.event.inputs.version }}"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create wheel
      run: |
        git tag v${{ env.TAG_STRING }}
        python -m pip install --upgrade pip
        python -m pip install wheel
        python setup.py bdist_wheel
        ls dist
    - name: Get version
      run: |
        echo "------------------------"
        echo "${{ env.TAG_STRING }}"
        ls dist
        echo "------------------------"

    - name: Release package
      uses: ncipollo/release-action@v1
      with:       
        tag: v${{ env.TAG_STRING }}
        name: Release v${{ env.TAG_STRING }}
        bodyFile: ./CHANGELOG.md
        artifacts: "./CHANGELOG.md"
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
