name: Create changelog and tag

on:
  workflow_run:
    workflows: ["Create changelog and tag"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      my_version:
        description: 'My version'
        required: true
        default: 'v0.0.10'
      my_description:
        description: 'My description'
        required: true
        default: 'Some text'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Create Version
      run: |
        echo "TAG_STRING=$(git describe --tags --abbrev=0 | sed -e s/v//g)" >> $GITHUB_ENV
    - name: Get version
      run: |
        echo "------------------------"
        echo "${{ env.TAG_STRING }}" 
        echo "------------------------"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install parse
    - name: Create changelog
      run: |        
        python3 scripts/release_notes.py -c create_release -i CURRENT_RELEASE_NOTE.md
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create wheel and publish to pypi
      env:
        PYPI_USER: ${{ secrets.PYPI_USER }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools_scm twine tox tox-wheel
        tox -e clean
        tox -e build
        tox -e publish -- -u${{ secrets.PYPI_USER }} -p"${{ secrets.PYPI_PASSWORD }}"
        ls dist
    - name: Release package
      uses: ncipollo/release-action@v1
      with:       
        tag: v${{ env.TAG_STRING }}
        name: Release v${{ env.TAG_STRING }}
        bodyFile: ./.tmprz/release_notes.md
        artifacts: dist/*.whl
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
